Update Dockerfile
Fix those errors (by updation ruby):

ERROR:  Error installing beanstalkd_view:
	rack requires Ruby version >= 2.2.2.
ERROR:  Error installing thin:
	rack requires Ruby version >= 2.2.2.